version: '3.8'

services:
  mongodb:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - /var/lib/connectly/mongodb:/data/db
      - /var/lib/connectly/mongodb-config:/data/configdb
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  server:
    environment:
      NODE_ENV: production
      MONGO_URI: ${MONGO_URI}
    volumes:
      - /var/lib/connectly/uploads:/app/uploads
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  client:
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/connectly/mongodb
  mongodb_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/connectly/mongodb-config
  server_uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/connectly/uploads